Documentation:
  Enabled: false

SignalException:
  EnforcedStyle: only_raise

TrailingComma:
  Enabled: false

Style/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/PredicateName:
  Exclude:
    - 'lib/poper/cli.rb'
